Added an end Date to IrImb DiagnosisExtractor
X-DataInitiative/SCALPEL-Extraction pull request #238
Opened 2020-02-14 17:02 UTC by strayMat

IrImb diagnosis should be handled carefully in studies. 

When used to characterize a patient, the IrImb diagnosis (ALD = Affection Longue Duree) should be active during the period of study. Thus we extract the endDate of ALD for IrImbDiagnosis.

2020-02-17 12:19 UTC, ysebiat requested changes
Some suggested changes.

2020-02-17 12:19 UTC, ysebiat commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/diagnoses/ImbDiagnosisExtractor.scala
> +import scala.util.Try
In the order of the imports, this should be first.

2020-02-17 12:19 UTC, ysebiat commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/diagnoses/ImbDiagnosisExtractor.scala
> +  def getEventEnd(r: Row): Timestamp = {
Can you document this method and why it defaults to 2100 when there is a missing value.

2020-02-17 15:59 UTC, strayMat commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/diagnoses/ImbDiagnosisExtractor.scala
> +import scala.util.Try
Changed.

2020-02-17 15:59 UTC, strayMat commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/diagnoses/ImbDiagnosisExtractor.scala
> +  def getEventEnd(r: Row): Timestamp = {
Changed to  return None if absent and documented irimb

2020-02-18 15:13 UTC, ysebiat approved these changes
LGTM.

2020-02-18 15:19 UTC, merged