Cnam-452: ExtractorCodes
X-DataInitiative/SCALPEL-Extraction pull request #250
Opened 2020-04-01 14:26 UTC by ysebiat

Refactoring the Extractor trait that aims to add coherence and reduce the redundancy of some codes parts.
Here are the changes:
1. Extractor trait has now a new `getCodes`method. It returns a `ExtractorCodes`type.
2. An `ExtractorCodes` is a trait that allows to pass a code that are more complex than a simple `Set`. This allows to have complex codes such as DrugConfig and NgapConfig.
3. A `BasicExtractor` is a new trait. It is intended for `Extractors`that are simple and that uses `EventRowExtractor` trait to get all the information from the `Row` to build an `Event`.
4. Every source, has now an implementation of `EventRowExtractor`implementation. This allows to unify the extraction of information of `Event` such patientID and groupID.

2020-04-03 17:15 UTC, Anfor reviewed
It miss some licenses enunciation and bad indentation in some files.

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/diagnoses/HadDiagnosisExtractor.scala
> +package fr.polytechnique.cmap.cnam.etl.extractors.events.diagnoses
You miss the license line

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/diagnoses/McoDiagnosisExtractor.scala
> +package fr.polytechnique.cmap.cnam.etl.extractors.events.diagnoses
License line?

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/diagnoses/SsrDiagnosisExtractor.scala
> +package fr.polytechnique.cmap.cnam.etl.extractors.events.diagnoses
Same this

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/drugs/classification/families/Cardiac.scala
> +    "3400933489045",
Why these spaces?

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/hospitalstays/HadHospitalStaysExtractor.scala
> +package fr.polytechnique.cmap.cnam.etl.extractors.events.hospitalstays
License?

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/hospitalstays/McoHospitalStaysExtractor.scala
> +package fr.polytechnique.cmap.cnam.etl.extractors.events.hospitalstays
Same here.

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/hospitalstays/McoceEmergenciesExtractor.scala
> +package fr.polytechnique.cmap.cnam.etl.extractors.events.hospitalstays
License

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/hospitalstays/SsrHospitalStaysExtractor.scala
> +package fr.polytechnique.cmap.cnam.etl.extractors.events.hospitalstays
License

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/takeoverreasons/HadTakeOverReasonExtractor.scala
> +package fr.polytechnique.cmap.cnam.etl.extractors.events.takeoverreasons
Same here

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/sources/had/HadRowExtractor.scala
> +package fr.polytechnique.cmap.cnam.etl.extractors.sources.had
License

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/sources/mco/McoRowExtractor.scala
> +      r.getAs[String](ColNames.RsaNum) + "_" +
not the same indentation

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/sources/ssr/SsrRowExtractor.scala
> +    r.getAs[String](ColNames.EtaNum) + "_" +
Indentation

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/study/bulk/BulkMain.scala
> +/*object BulkMain extends Main {
Why not remove it?

2020-04-03 17:15 UTC, Anfor commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/acts/DcirMedicalActsSuite.scala
> +    StructField(colNames.PatientID, StringType) ::
indentation

2020-04-03 17:15 UTC, Anfor commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/acts/DcirMedicalActsSuite.scala
> +    StructField(colNames.PatientID, StringType) ::
Same here

2020-04-03 17:15 UTC, Anfor commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/acts/DcirMedicalActsSuite.scala
> +  /*  "extract" should "return a Dataset of DCIR Medical Acts" in {
Is it used anymore? why not remove it?

2020-04-03 17:15 UTC, Anfor commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/hospitalstays/McoHospitalStayExtractorSuite.scala
> +    val result = df.map(r => McoHospitalStaysExtractor.extractWeight(r))
Better if it has the type.

2020-04-03 17:15 UTC, Anfor commented on src/main/scala/fr/polytechnique/cmap/cnam/study/pioglitazone/extractors/MedicalActs.scala
> +    //val cimActs = McoCimMedicalActExtractor(BaseExtractorCodes(config.mcoCIMCodes)).extract(sources)
Why not remove?

2020-04-03 17:15 UTC, Anfor commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/patients/HadPatientsSuite.scala
> +      ].toDF("patientID", "deathDate")
Bad indentation.

2020-04-03 17:15 UTC, Anfor commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/sources/ssr/SsrSourceSuite.scala
> +      val sqlCtx = sqlContext
Indentation

2020-04-07 08:56 UTC, dsun0720 requested changes
I like this new style of extractor. Good abstraction.

I agree with your code, only some places need to reformat the code that angel mentioned in the comments

2020-04-08 08:17 UTC, ysebiat commented on src/main/scala/fr/polytechnique/cmap/cnam/etl/extractors/sources/mco/McoRowExtractor.scala
> +      r.getAs[String](ColNames.RsaNum) + "_" +
That's the convention.

2020-04-08 08:17 UTC, ysebiat commented on src/main/scala/fr/polytechnique/cmap/cnam/study/bulk/BulkMain.scala
> +/*object BulkMain extends Main {
Because i will have to rebase it with the CNAM-450.

2020-04-08 08:18 UTC, ysebiat commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/acts/DcirMedicalActsSuite.scala
> +    StructField(colNames.PatientID, StringType) ::
That's the correct one.

2020-04-08 08:18 UTC, ysebiat commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/events/acts/DcirMedicalActsSuite.scala
> +    StructField(colNames.PatientID, StringType) ::
That's the correct format.

2020-04-08 08:18 UTC, ysebiat commented on src/main/scala/fr/polytechnique/cmap/cnam/study/pioglitazone/extractors/MedicalActs.scala
> +    //val cimActs = McoCimMedicalActExtractor(BaseExtractorCodes(config.mcoCIMCodes)).extract(sources)
Legacy.

2020-04-08 08:19 UTC, ysebiat commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/patients/HadPatientsSuite.scala
> +      ].toDF("patientID", "deathDate")
That's the correct format.

2020-04-08 08:20 UTC, ysebiat commented on src/test/scala/fr/polytechnique/cmap/cnam/etl/extractors/sources/ssr/SsrSourceSuite.scala
> +      val sqlCtx = sqlContext
That's the correct format.

2020-04-08 11:05 UTC, dsun0720 approved these changes

2020-04-08 12:03 UTC, merged